### ISSUE TITLE
PEP 681 support: Data Class Transforms

### ISSUE THREAD

**Issue by blakeNaccarato** [gahjelle/datadict#1]
I needed a dict-like dataclass and was going to implement it myself, but I did some Googling and found that your implementation does the trick. Thanks!

One minor issue I found is that your "dataclass-like" decorator isn't understood by type checkers like `mypy` and `pyright` as of now. This is a known limitation of user-defined dataclass-like functions, described and fixed in [PEP 681](https://peps.python.org/pep-0681/). The error given by `pyright` is `"Untyped class decorator obscures type of class; ignoring decorator"`.

If you're up for it, I can submit a Pull Request implementing this change. I recommend the "simple fix" below, which adds a dependency to `typing_extensions` (which itself requires Python 3.7 at minimum). But there's also a fix that doesn't add any dependencies, though it will bump your minimum supported Python to 3.8.

## Simple fix and an added dependency (dependency needs Python 3.7+)

The fix will be available in the standard library in 3.11, but is available today through [`typing_extensions`](https://pypi.org/project/typing-extensions/). Your package could be updated to support PEP 681 by adding the `typing_extensions` dependency and declaring the import:

```Python
from typing_extensions import dataclass_transform
```

And changing this:

https://github.com/gahjelle/datadict/blob/4e9fb67d9612f2d7fc9ba13fab4114193e051a41/datadict/dataclass.py#L6-L7

to this:

```Python
@dataclass_transform()
 def dataclass(cls=None, **kwargs): 
```

Since 3.11 will have `dataclass_transform` built in, `typing_extensions` conditionally chooses its own implementation for pre 3.11, and imports the built-in for 3.11 onward.

## More involved fix and no added dependencies (using Python 3.8+ protocols)

See the "Enforcing dataclasses" section of [this StackOverflow answer](https://stackoverflow.com/a/71617067).

**Comment by gahjelle** [comment]
Hi @blakeNaccarato 

Thanks for reaching out! I agree, it would be great to add PEP 681 support to `datadict`.

If you want to do the PR, I'd be very happy to merge it in to the code and publish a new version. 

I think the best solution is to use `typing_extensions`, the extra dependency is worth not cooking or own implementation.

**Comment by blakeNaccarato** [comment]
I've submitted the PR for this. Sorry about the spam of multiple "added a commit" messages above. I amended and force pushed in my own topic branch a few times. See my Pull Request for details on the changes. Thanks!

**Comment by blakeNaccarato** [comment]
Thanks for merging my Pull Request!

I've discovered a "gotcha" that I should point out to future readers: For those of you using `pyright`, you need to enable `useLibraryCodeForTypes` to benefit from this feature. From the [documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md):

> useLibraryCodeForTypes [boolean]: Determines whether pyright reads, parses and analyzes library code to extract type information in the absence of type stub files. Type information will typically be incomplete. We recommend using type stubs where possible. The default value for this option is false.
